"""move tasks and alerts to domain repositories

Revision ID: 3246a538de5a
Revises: 6d95c0bd1c4a
Create Date: 2026-08-21 16:52:46.744427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3246a538de5a'
down_revision = '6d95c0bd1c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('record_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    op.execute(sa.text(
        "UPDATE health_alerts SET alert_type = 'vital', "
        "record_date = DATE(created_at), description = content "
        "WHERE alert_type IS NULL OR record_date IS NULL OR description IS NULL"
    ))

    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.alter_column('alert_type', existing_type=sa.String(length=30), nullable=False)
        batch_op.alter_column('record_date', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('description', existing_type=sa.Text(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_alerts', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('record_date')
        batch_op.drop_column('alert_type')

    # ### end Alembic commands ###
