"""move ai conversations and messages to domain repositories

Revision ID: 645d5533beda
Revises: ab38bdc38add
Create Date: 2026-08-21 16:59:39.628782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645d5533beda'
down_revision = 'ab38bdc38add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=30), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('related_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_column('related_date')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
