"""move daily vitals and meals to domain repositories

Revision ID: 6d95c0bd1c4a
Revises: f17261d5d844
Create Date: 2026-08-21 16:20:20.842080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d95c0bd1c4a'
down_revision = 'f17261d5d844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    duplicate = op.get_bind().execute(sa.text(
        "SELECT daily_record_id FROM vital_records "
        "GROUP BY daily_record_id HAVING COUNT(*) > 1 LIMIT 1"
    )).first()
    if duplicate:
        raise RuntimeError(
            f"daily record {duplicate[0]} has multiple vital rows; clean duplicates before migration"
        )

    with op.batch_alter_table('meal_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_name', sa.String(length=30), server_default='加餐', nullable=False))

    with op.batch_alter_table('vital_records', schema=None) as batch_op:
        batch_op.create_unique_constraint('uk_vital_daily_record', ['daily_record_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_records', schema=None) as batch_op:
        batch_op.drop_constraint('uk_vital_daily_record', type_='unique')

    with op.batch_alter_table('meal_records', schema=None) as batch_op:
        batch_op.drop_column('meal_name')

    # ### end Alembic commands ###
