"""move reports and indicators to domain repositories

Revision ID: ab38bdc38add
Revises: 3246a538de5a
Create Date: 2026-08-21 16:56:49.380345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab38bdc38add'
down_revision = '3246a538de5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=30), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('report_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))

    op.execute(sa.text(
        "UPDATE medical_reports SET report_date = DATE(uploaded_at) WHERE report_date IS NULL"
    ))

    old_status = sa.Enum('uploaded', 'recognizing', 'recognized', 'review_pending', 'completed', 'failed', 'archived')
    new_status = sa.Enum('uploaded', 'recognizing', 'extracting', 'recognized', 'review_pending', 'completed', 'rejected', 'failed', 'archived')
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.alter_column('report_date', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('status', existing_type=old_status, type_=new_status, existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("UPDATE medical_reports SET status = 'failed' WHERE status = 'rejected'"))
    op.execute(sa.text("UPDATE medical_reports SET status = 'recognizing' WHERE status = 'extracting'"))
    old_status = sa.Enum('uploaded', 'recognizing', 'extracting', 'recognized', 'review_pending', 'completed', 'rejected', 'failed', 'archived')
    new_status = sa.Enum('uploaded', 'recognizing', 'recognized', 'review_pending', 'completed', 'failed', 'archived')
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=old_status, type_=new_status, existing_nullable=True)
        batch_op.drop_column('review_note')
        batch_op.drop_column('summary')
        batch_op.drop_column('progress')
        batch_op.drop_column('report_date')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
