"""move users profiles and settings to domain repositories

Revision ID: f17261d5d844
Revises: 3f1e73ba757d
Create Date: 2026-08-21 16:00:32.608172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17261d5d844'
down_revision = '3f1e73ba757d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chronic_types', sa.JSON(), nullable=True))

    op.execute(sa.text("UPDATE health_profiles SET chronic_types = '[]' WHERE chronic_types IS NULL"))

    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.alter_column('chronic_types', existing_type=sa.JSON(), nullable=False)
        batch_op.create_unique_constraint('uk_health_profile_user', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uk_health_profile_user', type_='unique')
        batch_op.drop_column('chronic_types')

    # ### end Alembic commands ###
